"""Draw the music video's plates: future postcards, the map, the daydream, the end card.

Run: python tools/music_video/postcards.py
Writes exports/music_video/plates/<plate>.png (1920 x 1080) and plates.json.

Every future-direction postcard carries an "IDEA - NOT BUILT YET" stamp and
names the design note it comes from; ideas are drawn only from
docs/FUTURE_LEVELS.md section 8 and docs/GAME_DESIGN.md. Everything is drawn
here with Pillow from the game's own shape language (sprites.py), seeded and
reproducible. Nothing is generated by a model or service.
"""
from __future__ import annotations

import json
import math
from pathlib import Path
import sys

import numpy as np
from PIL import Image, ImageDraw, ImageFilter

import song_data
from sprites import (COATS, CREAM, INK, LILAC, PARCHMENT, Pen, cultist, finish, font, helper,
                     listener)

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "exports" / "music_video" / "plates"
W, H, SS = 1920, 1080, 2
STAMP = "IDEA - NOT BUILT YET"
SEED = 2026_10_09

POSTCARDS = {  # plate: (place, subtitle, design-note source)
    "postcard-rosecourt": ("Rosecourt", "a noble garden gathering", "FUTURE_LEVELS section 8: noble garden gathering"),
    "postcard-tidemouth": ("Tidemouth", "harbour and docks", "FUTURE_LEVELS section 8: harbour and docks"),
    "postcard-lantern-fair": ("The Lantern Fair", "a travelling fair", "FUTURE_LEVELS section 8: travelling lantern fair"),
    "postcard-university": ("The University", "and its observatory", "FUTURE_LEVELS section 8: university and observatory"),
    "postcard-abbey": ("The Hilltop Abbey", "a pilgrimage", "FUTURE_LEVELS section 8: hilltop pilgrimage abbey"),
    "postcard-minions-magic": ("Helpers & Magic", "more hands, a little sparkle", "GAME_DESIGN: helpers, minions and magic"),
}


def canvas() -> tuple[Image.Image, Pen]:
    image = Image.fromarray(backdrop_array()).resize((W * SS, H * SS), Image.NEAREST).convert("RGBA")
    return image, Pen(image, SS)


def backdrop_array() -> np.ndarray:
    """The promo's dark lilac backdrop (tools/promo/render_promo.py), as an array."""
    y, x = np.mgrid[0:H, 0:W]
    glow = np.clip(1 - np.sqrt(((x - 960) / 1200) ** 2 + ((y - 480) / 800) ** 2), 0, 1)
    a = np.zeros((H, W, 3), dtype=np.uint8)
    for c, (base, lift) in enumerate([(17, 17), (11, 10), (28, 26)]):
        a[:, :, c] = base + lift * glow
    im = Image.fromarray(a)
    d = ImageDraw.Draw(im)
    for radius in (360, 470, 620, 780, 950):
        d.ellipse((960 - radius, 540 - radius, 960 + radius, 540 + radius), outline="#34213e", width=1)
    rng = np.random.default_rng(73)
    for _ in range(90):
        px, py = rng.integers(0, W), rng.integers(0, H)
        d.ellipse((px, py, px + 2, py + 2), fill="#634c74")
    return np.asarray(im)


def frame_pen(pen: Pen) -> Pen:
    """A fresh frame-space pen; sprite helpers move a shared pen's origin."""
    return Pen(pen.image, pen.ss).at(0, 0, 1)


def seal_border(pen: Pen, box, color=LILAC, ink=INK) -> None:
    x0, y0, x1, y1 = box
    p = frame_pen(pen)
    for inset, width, col in ((20, 3, ink), (32, 2, color)):
        p.line((x0 + inset, y0 + inset), (x1 - inset, y0 + inset), col, width)
        p.line((x1 - inset, y0 + inset), (x1 - inset, y1 - inset), col, width)
        p.line((x1 - inset, y1 - inset), (x0 + inset, y1 - inset), col, width)
        p.line((x0 + inset, y1 - inset), (x0 + inset, y0 + inset), col, width)
    for cx, cy in ((x0 + 26, y0 + 26), (x1 - 26, y0 + 26), (x0 + 26, y1 - 26), (x1 - 26, y1 - 26)):
        p.circle((cx, cy), 15, PARCHMENT)
        p.ring((cx, cy), 14, ink, 2)
        star = [(cx + 10 * math.cos(-math.pi / 2 + k * 4 * math.pi / 5),
                 cy + 10 * math.sin(-math.pi / 2 + k * 4 * math.pi / 5)) for k in range(6)]
        for a, b in zip(star, star[1:]):
            p.line(a, b, color, 1.5)


def paper(image: Image.Image, box, rng, tone=PARCHMENT) -> None:
    """A parchment card with a soft shadow and seeded fibres."""
    x0, y0, x1, y1 = [v * SS for v in box]
    shadow = Image.new("RGBA", image.size, (0, 0, 0, 0))
    ImageDraw.Draw(shadow).rounded_rectangle((x0 + 18, y0 + 24, x1 + 18, y1 + 24), 12 * SS, fill=(5, 2, 10, 150))
    image.alpha_composite(shadow.filter(ImageFilter.GaussianBlur(18 * SS)))
    d = ImageDraw.Draw(image, "RGBA")
    d.rounded_rectangle((x0, y0, x1, y1), 10 * SS, fill=tone)
    for _ in range(900):
        px, py = rng.uniform(x0, x1), rng.uniform(y0, y1)
        length = rng.uniform(3, 14) * SS
        angle = rng.uniform(0, math.pi)
        d.line((px, py, px + length * math.cos(angle), py + length * math.sin(angle)),
               fill=(120, 90, 60, int(rng.uniform(10, 28))), width=SS)


def stamp(image: Image.Image, text: str, centre, angle: float, rng, color=(164, 52, 72),
          size: int = 40) -> None:
    """A worn rubber stamp, rotated, with seeded ink gaps."""
    face = font(size * SS, serif=False, bold=True)
    probe = ImageDraw.Draw(image)
    tw = probe.textlength(text, font=face)
    pad = 26 * SS
    w, h = int(tw + 2 * pad), int(size * 2.5 * SS)
    layer = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    d = ImageDraw.Draw(layer)
    ink = color + (225,)
    d.rounded_rectangle((4 * SS, 4 * SS, w - 4 * SS, h - 4 * SS), 10 * SS, outline=ink, width=5 * SS)
    d.rounded_rectangle((13 * SS, 13 * SS, w - 13 * SS, h - 13 * SS), 6 * SS, outline=ink, width=2 * SS)
    d.text((w / 2, h / 2), text, font=face, fill=ink, anchor="mm")
    alpha = np.asarray(layer.getchannel("A")).astype(np.float32)
    worn = rng.uniform(.55, 1.0, (h // (3 * SS) + 1, w // (3 * SS) + 1))
    worn = np.kron(worn, np.ones((3 * SS, 3 * SS)))[:h, :w]
    layer.putalpha(Image.fromarray((alpha * worn).astype(np.uint8)))
    # A clean cream label behind the worn ink keeps the stamp legible on dark scenes.
    label = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    ImageDraw.Draw(label).rounded_rectangle((4 * SS, 4 * SS, w - 4 * SS, h - 4 * SS), 10 * SS,
                                            fill=(246, 236, 214, 235))
    label.alpha_composite(layer)
    layer = label
    layer = layer.rotate(angle, expand=True, resample=Image.BICUBIC)
    image.alpha_composite(layer, (int(centre[0] * SS - layer.width / 2), int(centre[1] * SS - layer.height / 2)))


# --- postcards -------------------------------------------------------------------

SCENE = (330, 330, 1590, 800)


def postcard(plate: str, rng) -> Image.Image:
    place, subtitle, source = POSTCARDS[plate]
    image, pen = canvas()
    card = (210, 95, 1710, 985)
    paper(image, card, rng)
    seal_border(pen, card)
    p = frame_pen(pen)
    p.text((960, 200), place, 76, INK, serif=True, bold=True)
    p.text((960, 268), subtitle, 30, "#6b4f7a", serif=True)
    x0, y0, x1, y1 = SCENE
    d = ImageDraw.Draw(image, "RGBA")
    scene = Image.new("RGBA", ((x1 - x0) * SS, (y1 - y0) * SS))
    SCENES[plate](Pen(scene, SS).at(0, 0, 1), scene, x1 - x0, y1 - y0, rng)
    mask = Image.new("L", scene.size, 0)
    ImageDraw.Draw(mask).rounded_rectangle((0, 0, scene.width - 1, scene.height - 1), 14 * SS, fill=255)
    image.paste(scene, (x0 * SS, y0 * SS), mask)
    d.rounded_rectangle((x0 * SS, y0 * SS, x1 * SS, y1 * SS), 14 * SS, outline=INK, width=3 * SS)
    p.text((960, 862), "A POSTCARD FROM SOMEDAY", 22, "#6b4f7a", serif=False, bold=True)
    p.text((960, 905), f"From the design notes ({source}). Not a promise.", 21, "#5a4a52", serif=False)
    stamp(image, STAMP, (1395, 372), 6, rng, size=32)
    return finish(image, SS)


def _sky(pen, w, h, top, bottom, ground, horizon=.62):
    d = pen.draw
    for i in range(h * SS):
        t = i / (h * SS)
        c = tuple(int(a + (b - a) * t) for a, b in zip(_rgb(top), _rgb(bottom)))
        d.line((0, i, w * SS, i), fill=c)
    d.rectangle((0, int(h * horizon * SS), w * SS, h * SS), fill=ground)


def _rgb(hex_):
    hex_ = hex_.lstrip("#")
    return tuple(int(hex_[i:i + 2], 16) for i in (0, 2, 4))


def rosecourt(pen, image, w, h, rng):
    _sky(pen, w, h, "#bcd6e6", "#e9efe0", "#8fb27a")
    for i in range(7):  # clipped hedges
        x = 40 + i * 180
        pen.at(0, 0, 1).circle((x + 70, 270), 75, "#55784a", squash=.55)
    pen.at(0, 0, 1).rect(0, 272, w, 20, "#4d6b42")
    for x in (120, 1120):  # rose bushes
        for k in range(5):
            pen.at(0, 0, 1).circle((x + rng.uniform(-30, 30), 310 + rng.uniform(-10, 10)), 8, "#c4566e")
    table = pen.at(0, 0, 1)
    table.rect(520, 352, 220, 12, "#7d5a3a")
    table.rect(530, 364, 8, 50, "#6a4b30")
    table.rect(722, 364, 8, 50, "#6a4b30")
    for cx in (560, 610, 690):
        table.circle((cx, 346), 9, "#f6efe3", squash=.6)
    listener(pen, 470, 425, 2.4, COATS[3], "patron")
    listener(pen, 800, 425, 2.4, COATS[1], "patron")
    listener(pen, 640, 448, 2.4, "#a07aae", "fan")
    pen.at(800, 425, 2.4).line((-10, -20), (-16, -40), "#f1dfb1", 2)  # the host's raised toast
    cultist(pen, 330, 440, 2.4)
    listener(pen, 1080, 445, 2.4, COATS[5], "pie")  # Gerald arrives, with the pie
    pen.at(0, 0, 1).text((1080, 315), "Gerald", 20, "#3b2a45", serif=True)


def tidemouth(pen, image, w, h, rng):
    _sky(pen, w, h, "#b7cde0", "#e3ebf0", "#5f88a3", horizon=.5)
    p = pen.at(0, 0, 1)
    for i in range(6):  # gentle waves
        y = 260 + i * 34
        for x in range(0, w, 90):
            p.arc((x + (i % 2) * 45, y), 22, math.pi * 1.1, math.pi * 1.9, "#8fb0c6", 2)
    p.rect(0, 380, 620, 30, "#8c6a48")  # quays
    p.rect(760, 380, w - 760, 30, "#8c6a48")
    for x in range(0, w, 60):
        p.line((x, 380), (x, 410), "#6d5137", 2)
    p.arc((690, 420), 90, math.pi, math.tau, "#7a5a3c", 10)  # a crossing between quays
    p.poly([(900, 340), (1180, 340), (1150, 380), (930, 380)], "#6b4a35")  # a ship
    p.line((1040, 340), (1040, 170), "#5a3f2c", 6)
    p.poly([(1046, 180), (1046, 320), (1150, 320)], "#f3ead6")
    p.poly([(1034, 190), (1034, 320), (950, 320)], "#e7dcc4")
    a = pen.at(260, 360, 1)  # anchor on the quay
    a.line((0, -50), (0, 0), "#3d3a42", 6)
    a.arc((0, -15), 22, 0, math.pi, "#3d3a42", 6)
    a.line((-14, -42), (14, -42), "#3d3a42", 5)
    a.ring((0, -56), 7, "#3d3a42", 4)
    listener(pen, 500, 395, 2.4, COATS[2], "captain")
    listener(pen, 1150, 395, 2.2, COATS[4], "guild")
    listener(pen, 1250, 395, 2.2, COATS[0])
    pen.at(1250, 395, 2.2).line((10, -20), (30, -50), "#6a5136", 2)  # a fishing rod
    cultist(pen, 360, 405, 2.4)


def lantern_fair(pen, image, w, h, rng):
    _sky(pen, w, h, "#2c2346", "#4a3a5e", "#5b4a3e", horizon=.58)
    p = pen.at(0, 0, 1)
    cx, cy = w / 2, 380
    for k in range(10):  # radial lanes
        angle = math.pi * (k / 9)
        p.line((cx, cy), (cx + 900 * math.cos(angle), cy + 260 * math.sin(angle)), "#6d5a49", 3)
    p.ring((cx, cy), 150, "#d8b06a", 4, squash=.3)
    for row, y in enumerate((60, 110)):  # strings of lanterns
        pts = [(x, y + 40 * math.sin(math.pi * x / w)) for x in range(0, w + 1, 40)]
        for a, b in zip(pts, pts[1:]):
            p.line(a, b, "#1c1528", 2)
        for i, (x, y2) in enumerate(pts[1:-1:2]):
            p.circle((x, y2 + 16), 16, (255, 207, 110, 60))
            p.circle((x, y2 + 14), 9, "#ffcf6e" if (i + row) % 3 else "#f39a6b")
    p.poly([(90, 250), (430, 250), (410, 300), (110, 300)], "#c94f4f")  # a stall
    for i in range(6):
        p.rect(100 + i * 55, 250, 28, 50, "#f2e5c8")
    p.rect(120, 300, 280, 110, "#7a5a3c")
    p.rect(140, 318, 240, 44, "#f3e6c6")
    p.text((260, 340), "JOIN US", 26, "#6f4593", serif=True, bold=True)
    p.text((260, 384), "(free biscuits)", 16, "#f3e6c6", serif=True)
    cultist(pen, 470, 455, 1.9)  # one stall is clearly recruitment
    listener(pen, cx, 420, 2.4, "#b8423f", "top_hat")
    for i, x in enumerate((780, 860, 1040, 1120)):
        listener(pen, x, 440 + (i % 2) * 10, 2.0, COATS[i])


def university(pen, image, w, h, rng):
    _sky(pen, w, h, "#d6d0e6", "#ece6f2", "#a7a08a", horizon=.66)
    p = pen.at(0, 0, 1)
    for x0 in (30, 860):  # two courtyards
        p.rect(x0, 120, 370, 200, "#c9b89a")
        p.poly([(x0 - 10, 120), (x0 + 185, 50), (x0 + 380, 120)], "#8e6f5a")
        for k in range(4):
            wx = x0 + 30 + k * 85
            p.rect(wx, 180, 40, 60, "#5d5072")
            p.circle((wx + 20, 180), 20, "#5d5072")
    p.rect(400, 300, 460, 20, "#c3b48e")  # the library path
    for x, flip in ((470, 1), (790, -1)):  # a telescope pointed at another telescope
        t = pen.at(x, 420, 1)
        t.line((0, 0), (-24, 60), "#4b3d36", 5)
        t.line((0, 0), (24, 60), "#4b3d36", 5)
        t.line((0, 0), (0, 60), "#4b3d36", 5)
        t.line((-60 * flip, 18), (70 * flip, -30), "#7a6a8e", 18)
        t.line((70 * flip, -30), (88 * flip, -36), "#d8c26a", 20)
    listener(pen, 630, 470, 2.5, "#3b3448", "mortarboard")
    listener(pen, 250, 480, 2.2, COATS[1], "scholar")
    listener(pen, 1050, 480, 2.2, COATS[2], "scholar")
    cultist(pen, 160, 486, 2.2)


def abbey(pen, image, w, h, rng):
    _sky(pen, w, h, "#e9d7b9", "#f3e8d6", "#a9b07e", horizon=.9)
    p = pen.at(0, 0, 1)
    for i in range(5):  # terraces
        y = 430 - i * 60
        p.poly([(80 + i * 90, y), (w - 80 - i * 90, y), (w - 120 - i * 90, y + 60), (120 + i * 90, y + 60)],
               ["#9aa673", "#a9b07e", "#b6b98a", "#c3c296", "#cfcaa2"][i])
    for i in range(10):  # the broad central stair
        y = 470 - i * 30
        p.rect(560 + i * 4, y, 140 - i * 8, 8, "#d9cdb0")
    p.rect(520, 60, 220, 120, "#d8c9a8")  # the abbey
    p.poly([(505, 60), (630, 0), (755, 60)], "#8b6a55")
    p.rect(600, 110, 60, 70, "#4b3d50")
    p.circle((630, 110), 30, "#4b3d50")
    p.rect(700, 10, 40, 70, "#cbbb98")
    p.poly([(694, 10), (720, -30), (746, 10)], "#8b6a55")
    listener(pen, 820, 200, 2.0, "#3c3448", "wimple")
    for i, (x, y) in enumerate(((610, 470), (650, 410), (610, 350), (655, 290))):  # only four cultists
        cultist(pen, x, y, 1.15)
    pen.at(0, 0, 1).text((230, 440), "(genuinely small again)", 24, "#5a4a52", serif=True)


def minions_magic(pen, image, w, h, rng):
    _sky(pen, w, h, "#241b38", "#3b2d55", "#4a3d5a", horizon=.7)
    p = pen.at(0, 0, 1)
    for r, alpha in ((260, 30), (200, 45), (150, 60)):  # a glowing reach ring
        p.ring((360, 420), r, (212, 180, 250, alpha), 10, squash=.32)
    p.ring((360, 420), 240, LILAC, 3, squash=.32)
    for _ in range(60):
        x, y = rng.uniform(0, w), rng.uniform(0, h * .55)
        p.circle((x, y), rng.uniform(1, 2.5), (240, 230, 255, int(rng.uniform(60, 180))))
    cultist(pen, 360, 430, 2.5)
    s = pen.at(430, 310, 1)  # one polite spark
    s.poly([(0, -18), (5, -5), (18, 0), (5, 5), (0, 18), (-5, 5), (-18, 0), (-5, -5)], "#ffe4a1")
    for i in range(7):  # helpers keep arriving
        helper(pen, 640 + i * 95, 440 + (i % 2) * 14, 2.3 - i * .08)
    pen.at(0, 0, 1).text((1000, 300), "helpers keep arriving", 22, "#d8c8ec", serif=True)


SCENES = {"postcard-rosecourt": rosecourt, "postcard-tidemouth": tidemouth,
          "postcard-lantern-fair": lantern_fair, "postcard-university": university,
          "postcard-abbey": abbey, "postcard-minions-magic": minions_magic}


# --- other plates ----------------------------------------------------------------

def map_three_pins(rng) -> Image.Image:
    image, pen = canvas()
    card = (150, 80, 1770, 1000)
    paper(image, card, rng, "#eadbb9")
    seal_border(pen, card)
    p = frame_pen(pen)
    p.text((960, 175), "OUR WORLDWIDE REACH", 64, INK, serif=True, bold=True)
    # A whole invented continent, with a coastline of seeded wobble.
    pts = []
    for k in range(80):
        a = math.tau * k / 80
        r = 330 * (1 + .18 * math.sin(3 * a + 1) + .1 * math.sin(7 * a) + .05 * rng.normal())
        pts.append((760 + 1.55 * r * math.cos(a), 590 + .9 * r * math.sin(a)))
    p.poly(pts, "#cdb98a")
    for a, b in zip(pts, pts[1:] + pts[:1]):
        p.line(a, b, "#7a6244", 3)
    p.text((760, 470), "THE WORLD", 34, "#8a7354", serif=True)
    for dx, dy in ((0, 0), (14, 6), (5, 16)):  # three pins, very close together
        x, y = 980 + dx, 640 + dy
        p.line((x, y), (x, y - 26), "#4b3d36", 3)
        p.circle((x, y - 30), 8, "#c4475a")
    p.text((990, 700), "Bramblewick", 24, INK, serif=True, bold=True)
    p.ring((1450, 600), 170, INK, 5)  # magnifier inset
    p.circle((1450, 600), 165, "#d9c79c")
    for dx, dy in ((-60, 10), (30, -40), (50, 60)):
        x, y = 1450 + dx, 600 + dy
        p.line((x, y), (x, y - 70), "#4b3d36", 6)
        p.circle((x, y - 80), 20, "#c4475a")
    p.line((1330, 720), (1100, 655), INK, 3)
    p.text((960, 940), "*within walking distance", 34, "#6b4f7a", serif=True)
    return finish(image, SS)


def vision_enormous(rng) -> Image.Image:
    image, pen = canvas()
    d = ImageDraw.Draw(image, "RGBA")
    for i in range(H * SS):  # golden haze
        t = i / (H * SS)
        d.line((0, i, W * SS, i), fill=(int(245 - 90 * t), int(205 - 110 * t), int(130 - 80 * t)))
    p = frame_pen(pen)
    for k in range(9):  # towers and banners on the horizon
        x = 120 + k * 210 + rng.uniform(-30, 30)
        height = rng.uniform(180, 340)
        p.rect(x, 520 - height, 70, height, "#8a5d6c")
        p.poly([(x - 10, 520 - height), (x + 35, 450 - height), (x + 80, 520 - height)], "#5a3a55")
        p.line((x + 35, 450 - height), (x + 35, 400 - height), "#3b2a45", 3)
        p.poly([(x + 35, 400 - height), (x + 85, 412 - height), (x + 35, 424 - height)], "#9670ad")
    for k in range(5):  # ships far away
        x = 200 + k * 360
        p.poly([(x, 548), (x + 90, 548), (x + 75, 566), (x + 15, 566)], "#5a3a45")
        p.poly([(x + 45, 548), (x + 45, 500), (x + 80, 548)], "#f3ead6")
    p.rect(0, 560, W, H - 560, "#b27a5b")
    for row in range(14):  # hundreds of followers, row after row
        y = 600 + row * 34
        s = .45 + row * .07
        count = 22 - row // 2
        for i in range(count):
            x = (i + .5 + (row % 2) * .5) * W / count + rng.uniform(-8, 8)
            cultist(pen, x, y + rng.uniform(-4, 4), s)
    stamp(image, "DAYDREAM", (1550, 170), -6, rng, color=(120, 70, 30))
    return finish(image, SS)


def end_card(rng) -> Image.Image:
    image, pen = canvas()
    p = frame_pen(pen)
    p.rect(400, 300, 1120, 154, "#8a6440")  # the hand-painted sign
    p.line((400, 377), (1520, 377), "#7d5a3a", 3)
    p.line((400, 454), (1520, 454), "#5a3f2a", 3)
    p.line((560, 454), (560, 700), "#5a3f2a", 12)
    p.line((1360, 454), (1360, 700), "#5a3f2a", 12)
    p.text((960, 377), "SMALL FOLLOWING", 84, CREAM, serif=True, bold=True)
    p.line((800, 470), (790, 560), "#3b2a20", 3)  # the queue plank
    p.line((1120, 470), (1130, 560), "#3b2a20", 3)
    p.rect(700, 560, 520, 60, "#b38c5c")
    p.text((960, 590), "PLEASE FORM AN ORDERLY QUEUE", 30, "#3b2a20", serif=False, bold=True)
    cultist(pen, 1640, 760, 3.0)
    p = frame_pen(pen)
    p.text((960, 880), "Gameplay shots are real play. Staged shots use the game's own art.", 26, LILAC,
           serif=False)
    p.text((960, 930), "Some of these places may happen. None of them are promises.", 26, CREAM,
           serif=True)
    return finish(image, SS)


OTHER = {"map-three-pins": map_three_pins, "vision-enormous": vision_enormous, "end-card": end_card}


def main() -> int:
    song = song_data.load()
    errors = song_data.validate(song)
    if errors:
        print("\n".join("ERROR: " + e for e in errors))
        return 1
    OUT.mkdir(parents=True, exist_ok=True)
    manifest = []
    labels = {shot["plate"]: shot.get("label", "") for shot in song["shots"] if "plate" in shot}
    for index, plate in enumerate(song["plates"]):
        rng = np.random.default_rng([SEED, index])
        if plate in POSTCARDS:
            if "NOT BUILT" not in labels.get(plate, ""):
                print(f"ERROR: {plate} is a future idea but its shot is not labelled NOT BUILT")
                return 1
            image = postcard(plate, rng)
            source = POSTCARDS[plate][2]
        elif plate in OTHER:
            image = OTHER[plate](rng)
            source = "music video plate"
        else:
            print(f"ERROR: no painter for plate {plate!r}")
            return 1
        path = OUT / f"{plate}.png"
        image.convert("RGB").save(path, optimize=True)
        manifest.append({"plate": plate, "file": path.name, "label": labels.get(plate, ""),
                         "stamp": STAMP if plate in POSTCARDS else ("DAYDREAM" if plate == "vision-enormous" else ""),
                         "source": source})
        print(f"{path.name}: {image.width}x{image.height}  {manifest[-1]['stamp'] or '-'}  ({source})")
    (OUT / "plates.json").write_text(json.dumps(manifest, indent=1), encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
